import math

import numpy as np

MATCHING_WEIGHTS_LIMITS = (1, 100)

NUM_LEFT = 10
NUM_RIGHT = NUM_LEFT

NUM_AGENTS = NUM_LEFT

PROPORTION_OF_EDGES_PER_SUBGRAPH = 1 / math.sqrt(NUM_AGENTS)

CONNECTIVITY_GRAPH_EDGE_PROPORTION = 1 / np.sqrt(NUM_AGENTS)

DISCREPANCY_THRESHOLD = 0.25 * min(NUM_RIGHT, NUM_LEFT)

MIN_ALLOWED_MATCHING_SCORE_PROPORTION = 0.9
